<?php
/**
 * Created by PhpStorm.
 * User: codimiracle
 * Date: 18-1-25
 * Time: 下午10:54
 */

namespace CAstore\Component;

use PHPUnit\Framework\TestCase;

class NodePathTest extends TestCase
{
    /**
     * @var NodePath
     */
    private $nodePath;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->nodePath = new NodePath("/Node");
    }

    public function testToString() {
        self::assertEquals("/Node", strval($this->nodePath));
    }


    public function testMainNodeName() {
        self::assertEquals("Node", $this->nodePath->getMainNodeName());
    }

    public function testSubNodePath() {
        self::assertEquals(strval($this->nodePath->getSubnodePath()), strval(new NodePath("/")));
    }
}
